export const data = {
  player_data: [
    {
      Age: '21',
      Birthday: '2002.03.03',
      Birthplace: 'Carrara, Italy',
      'Career high': '18',
      Coach: 'Simone Tartarini',
      'Date careeer High': '2023.01.30',
      'Flag Code': 'ITA',
      Image: 'https://www.atptour.com/-/media/tennis/players/gladiator/2022/06/16/23/49/musetti-full-2022-june-1.png',
      Name: 'Lorenzo Musetti',
      'Play Style': 'Right-Handed, One-Handed Backhand',
      'Prize money 2023': '$899,716',
      'Prize money Career': '$3,625,945',
      Rank: '18',
      'Rank 2023': '18',
      'Rank diff 2023': '',
      'TItles Career': '2',
      'Titles 2023': '0',
      'W/L 2023': '13-12',
      'W/L Career': '73-66',
      'Year Turned Pro': '2019',
      'height(cm)': '185cm',
      'height(ft)': '6"1"',
      'weight(kgs)': '78kg',
      'weight(lbs)': '172',
    },
  ],
};

export const players_list = {
  category: 'singles',
  data: [
    {
      Age: 20,
      Name: 'Carlos Alcaraz',
      Points: 6815,
      Rank: 1,
      'Rank Diff': '0',
      id: 'a0e2',
    },
    {
      Age: 27,
      Name: 'Daniil Medvedev',
      Points: 6330,
      Rank: 2,
      'Rank Diff': '0',
      id: 'mm58',
    },
    {
      Age: 36,
      Name: 'Novak Djokovic',
      Points: 5955,
      Rank: 3,
      'Rank Diff': '0',
      id: 'd643',
    },
    {
      Age: 24,
      Name: 'Casper Ruud',
      Points: 4960,
      Rank: 4,
      'Rank Diff': '0',
      id: 'rh16',
    },
    {
      Age: 24,
      Name: 'Stefanos Tsitsipas',
      Points: 4775,
      Rank: 5,
      'Rank Diff': '0',
      id: 'te51',
    },
    {
      Age: 20,
      Name: 'Holger Rune',
      Points: 4375,
      Rank: 6,
      'Rank Diff': '0',
      id: 'r0dg',
    },
    {
      Age: 25,
      Name: 'Andrey Rublev',
      Points: 4270,
      Rank: 7,
      'Rank Diff': '0',
      id: 're44',
    },
    {
      Age: 25,
      Name: 'Taylor Fritz',
      Points: 3470,
      Rank: 8,
      'Rank Diff': 1,
      id: 'fb98',
    },
    {
      Age: 21,
      Name: 'Jannik Sinner',
      Points: 3435,
      Rank: 9,
      'Rank Diff': -1,
      id: 's0ag',
    },
    {
      Age: 22,
      Name: 'Felix Auger-Aliassime',
      Points: 3100,
      Rank: 10,
      'Rank Diff': '0',
      id: 'ag37',
    },
    {
      Age: 27,
      Name: 'Karen Khachanov',
      Points: 2945,
      Rank: 11,
      'Rank Diff': '0',
      id: 'ke29',
    },
    {
      Age: 25,
      Name: 'Frances Tiafoe',
      Points: 2790,
      Rank: 12,
      'Rank Diff': '0',
      id: 'td51',
    },
    {
      Age: 27,
      Name: 'Cameron Norrie',
      Points: 2565,
      Rank: 13,
      'Rank Diff': 1,
      id: 'n771',
    },
    {
      Age: 26,
      Name: 'Hubert Hurkacz',
      Points: 2525,
      Rank: 14,
      'Rank Diff': -1,
      id: 'hb71',
    },
    {
      Age: 36,
      Name: 'Rafael Nadal',
      Points: 2445,
      Rank: 15,
      'Rank Diff': '0',
      id: 'n409',
    },
    {
      Age: 26,
      Name: 'Borna Coric',
      Points: 2410,
      Rank: 16,
      'Rank Diff': '0',
      id: 'cg80',
    },
    {
      Age: 26,
      Name: 'Tommy Paul',
      Points: 2170,
      Rank: 17,
      'Rank Diff': '0',
      id: 'pl56',
    },
    {
      Age: 21,
      Name: 'Lorenzo Musetti',
      Points: 2040,
      Rank: 18,
      'Rank Diff': '0',
      id: 'm0ej',
    },
    {
      Age: 24,
      Name: 'Alex de Minaur',
      Points: 1870,
      Rank: 19,
      'Rank Diff': '0',
      id: 'dh58',
    },
    {
      Age: 27,
      Name: 'Matteo Berrettini',
      Points: 1832,
      Rank: 20,
      'Rank Diff': '0',
      id: 'bk40',
    },
    {
      Age: 31,
      Name: 'Pablo Carreno Busta',
      Points: 1740,
      Rank: 21,
      'Rank Diff': '0',
      id: 'cd85',
    },
    {
      Age: 34,
      Name: 'Marin Cilic',
      Points: 1510,
      Rank: 22,
      'Rank Diff': '0',
      id: 'c977',
    },
    {
      Age: 24,
      Name: 'Francisco Cerundolo',
      Points: 1485,
      Rank: 23,
      'Rank Diff': 5,
      id: 'c0au',
    },
    {
      Age: 35,
      Name: 'Roberto Bautista Agut',
      Points: 1485,
      Rank: 24,
      'Rank Diff': -1,
      id: 'bd06',
    },
    {
      Age: 33,
      Name: 'Daniel Evans',
      Points: 1480,
      Rank: 25,
      'Rank Diff': -1,
      id: 'e687',
    },
    {
      Age: 28,
      Name: 'Nick Kyrgios',
      Points: 1465,
      Rank: 26,
      'Rank Diff': -1,
      id: 'ke17',
    },
    {
      Age: 26,
      Name: 'Alexander Zverev',
      Points: 1450,
      Rank: 27,
      'Rank Diff': '0',
      id: 'z355',
    },
    {
      Age: 33,
      Name: 'Jan-Lennard Struff',
      Points: 1447,
      Rank: 28,
      'Rank Diff': -2,
      id: 'sl28',
    },
    {
      Age: 32,
      Name: 'Grigor Dimitrov',
      Points: 1275,
      Rank: 29,
      'Rank Diff': 4,
      id: 'd875',
    },
    {
      Age: 22,
      Name: 'Sebastian Korda',
      Points: 1265,
      Rank: 30,
      'Rank Diff': -1,
      id: 'k0ah',
    },
    {
      Age: 27,
      Name: 'Botic van de Zandschulp',
      Points: 1215,
      Rank: 31,
      'Rank Diff': -1,
      id: 'v812',
    },
    {
      Age: 24,
      Name: 'Denis Shapovalov',
      Points: 1210,
      Rank: 32,
      'Rank Diff': -1,
      id: 'su55',
    },
    {
      Age: 27,
      Name: 'Yoshihito Nishioka',
      Points: 1181,
      Rank: 33,
      'Rank Diff': -1,
      id: 'n732',
    },
    {
      Age: 23,
      Name: 'Alejandro Davidovich Fokina',
      Points: 1115,
      Rank: 34,
      'Rank Diff': '0',
      id: 'dh50',
    },
    {
      Age: 27,
      Name: 'Nicolas Jarry',
      Points: 1112,
      Rank: 35,
      'Rank Diff': 19,
      id: 'j551',
    },
    {
      Age: 20,
      Name: 'Ben Shelton',
      Points: 1095,
      Rank: 36,
      'Rank Diff': -1,
      id: 's0s1',
    },
    {
      Age: 23,
      Name: 'Miomir Kecmanovic',
      Points: 1065,
      Rank: 37,
      'Rank Diff': -1,
      id: 'ki95',
    },
    {
      Age: 26,
      Name: 'Bernabe Zapata Miralles',
      Points: 1051,
      Rank: 38,
      'Rank Diff': -1,
      id: 'z419',
    },
    {
      Age: 26,
      Name: 'Tallon Griekspoor',
      Points: 1034,
      Rank: 39,
      'Rank Diff': '0',
      id: 'gj37',
    },
    {
      Age: 24,
      Name: 'Ugo Humbert',
      Points: 1026,
      Rank: 40,
      'Rank Diff': -2,
      id: 'hh26',
    },
    {
      Age: 21,
      Name: 'Jiri Lehecka',
      Points: 994,
      Rank: 41,
      'Rank Diff': -1,
      id: 'l0bv',
    },
    {
      Age: 22,
      Name: 'Sebastian Baez',
      Points: 990,
      Rank: 42,
      'Rank Diff': 2,
      id: 'b0bi',
    },
    {
      Age: 36,
      Name: 'Andy Murray',
      Points: 975,
      Rank: 43,
      'Rank Diff': -2,
      id: 'mc10',
    },
    {
      Age: 26,
      Name: 'Maxime Cressy',
      Points: 975,
      Rank: 44,
      'Rank Diff': -2,
      id: 'c0bc',
    },
    {
      Age: 21,
      Name: 'Brandon Nakashima',
      Points: 957,
      Rank: 45,
      'Rank Diff': 7,
      id: 'n0ae',
    },
    {
      Age: 24,
      Name: 'Emil Ruusuvuori',
      Points: 956,
      Rank: 46,
      'Rank Diff': -3,
      id: 'rh24',
    },
    {
      Age: 34,
      Name: 'Adrian Mannarino',
      Points: 937,
      Rank: 47,
      'Rank Diff': '0',
      id: 'me82',
    },
    {
      Age: 28,
      Name: 'Lorenzo Sonego',
      Points: 925,
      Rank: 48,
      'Rank Diff': -3,
      id: 'su87',
    },
    {
      Age: 23,
      Name: 'Tomas Martin Etcheverry',
      Points: 920,
      Rank: 49,
      'Rank Diff': -3,
      id: 'ea24',
    },
    {
      Age: 24,
      Name: 'J.J. Wolf',
      Points: 915,
      Rank: 50,
      'Rank Diff': -1,
      id: 'w09g',
    },
  ],
  timestamp: 'current',
};
